### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by nguyenbathanh** [ssolidus/vscode-mactype-hack#1]
![screenshot_7](https://user-images.githubusercontent.com/4046112/33491144-ee14441c-d6eb-11e7-8577-dabc628beaa4.png)
![screenshot_8](https://user-images.githubusercontent.com/4046112/33491146-ee60ce2c-d6eb-11e7-9b7a-8cc83521ba5a.png)
![screenshot_9](https://user-images.githubusercontent.com/4046112/33491148-ee9580cc-d6eb-11e7-9e59-e9a2ceeb76d9.png)

**Comment by thomasklash** [comment]
Hi,

It looks like the latest version of Chromium has dropped the `--disable-direct-write` flag, causing this hack to break.

**Comment by ssolidus** [comment]
I saw your post here: https://github.com/snowie2000/mactype/issues/388

Have you found anything since?

**Comment by nguyenbathanh** [comment]
I didn't. I decided using Sublime Text with GDI support, Chromium sucks.

**Comment by ssolidus** [comment]
Closing due to upstream deprecation of feature

**Comment by dmxt** [comment]
Is this repo depreciated?
